[project]
name = "jphandwritingmodel"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Reese D.", email = "61914473+fenreese@users.noreply.github.com" }
]
dependencies = [
    "fastapi[standard]>=0.115.4",
    "python-multipart>=0.0.17",
    "pillow>=11.0.0"
]
readme = "README.md"
requires-python = ">= 3.12"

[tool.rye]
managed = true
virtual = true
dev-dependencies = [
    "tensorflow>=2.18.0",
    "numpy>=2.1.3",
]
